# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c52a554be75a081da6d51c9b30ca7753f75bef9076e0b1e135c4b54289c9b5fac3f2350f60c8ac5f0e6b4d046102e85b13c07a0483f62113e131ac090dfd9efa

test:
  secret_key_base: 6e9c2918cdfd9c05d16eaec3bb7f6d6e00bab49c653d4d59b335a9001a1c209239ee637f78c0f3c110450b2b0e971199a9ddb41c5dbb44110d223c3eba90aa78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
